/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyekpbonew;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author Inghwe
 */
public class FrameUser extends javax.swing.JFrame {

    /**
     * Creates new form FrameUser
     */
    public FrameUser() {
        initComponents();
        this.setTitle("Menu User");

        //set width, height frame admin
        this.setSize(1100, 700);

        //set width, height background image frame admin
        this.getBackgroundImage().setSize(1100, 700);

        //set button frame admin
        this.getGameBtn().setBounds(450, 100, 150, 50);
        this.getMainBtn().setBounds(450, 200, 150, 50);
        this.getLeaderboardBtn().setBounds(450, 300, 150, 50);
        this.getLogoutBtn().setBounds(450, 400, 150, 50);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GameBtn = new javax.swing.JToggleButton();
        MainBtn = new javax.swing.JToggleButton();
        LeaderboardBtn = new javax.swing.JToggleButton();
        logoutBtn = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("USER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(186, 37, 28, 16);

        GameBtn.setText("GAME");
        GameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameBtnActionPerformed(evt);
            }
        });
        getContentPane().add(GameBtn);
        GameBtn.setBounds(169, 71, 63, 22);

        MainBtn.setText("MAIN");
        MainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MainBtn);
        MainBtn.setBounds(169, 114, 60, 22);

        LeaderboardBtn.setText("LEADERBOARD");
        LeaderboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaderboardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LeaderboardBtn);
        LeaderboardBtn.setBounds(144, 157, 112, 22);

        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn);
        logoutBtn.setBounds(164, 210, 76, 22);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/background.jpg"))); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 410, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GameBtnActionPerformed

    private void MainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainBtnActionPerformed
        if (ProyekPBONew.getLoggedUser().getSaldo() > 0) {
            ProyekPBONew.getFrameGame().setVisible(true);
            ProyekPBONew.getFrameGame().getCurSaldo().setText("$" + ProyekPBONew.getLoggedUser().getSaldo());
        }
    }//GEN-LAST:event_MainBtnActionPerformed

    private void LeaderboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaderboardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeaderboardBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ProyekPBONew.getLogframe().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    public JToggleButton getGameBtn() {
        return GameBtn;
    }

    public JToggleButton getLeaderboardBtn() {
        return LeaderboardBtn;
    }

    public JToggleButton getMainBtn() {
        return MainBtn;
    }

    public JButton getLogoutBtn() {
        return logoutBtn;
    }

    public JLabel getBackgroundImage() {
        return backgroundImage;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton GameBtn;
    private javax.swing.JToggleButton LeaderboardBtn;
    private javax.swing.JToggleButton MainBtn;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutBtn;
    // End of variables declaration//GEN-END:variables
}
