/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyekpbonew;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Gary
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        this.setSize(1920, 1080);
        this.getBetField().setBounds(675, 162, 250, 30);
        this.getBetLabel().setBounds(550, 150, 250, 50);
        this.getBetConfirm().setBounds(590, 400, 250, 50);
        this.getCurSaldo().setBounds(675, 100, 250, 50);
        this.getSaldoLabel().setBounds(590, 100, 250, 50);
        this.setLocationRelativeTo(null);
    }

    public JLabel getSaldoLabel() {
        return SaldoLabel;
    }

    public JButton getBetConfirm() {
        return BetConfirm;
    }

    public JLabel getCurSaldo() {
        return CurSaldo;
    }

    public JTextField getBetField() {
        return BetField;
    }

    public JLabel getBetLabel() {
        return BetLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BetLabel = new javax.swing.JLabel();
        BetField = new javax.swing.JTextField();
        BetConfirm = new javax.swing.JButton();
        CurSaldo = new javax.swing.JLabel();
        SaldoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BetLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BetLabel.setText("Input Bet :");
        getContentPane().add(BetLabel);
        BetLabel.setBounds(93, 107, 65, 32);

        BetField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(BetField);
        BetField.setBounds(180, 110, 103, 20);

        BetConfirm.setText("OK");
        BetConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(BetConfirm);
        BetConfirm.setBounds(140, 150, 72, 22);

        CurSaldo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CurSaldo.setText("jLabel1");
        getContentPane().add(CurSaldo);
        CurSaldo.setBounds(140, 80, 37, 32);

        SaldoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SaldoLabel.setText("Saldo :");
        getContentPane().add(SaldoLabel);
        SaldoLabel.setBounds(90, 80, 37, 32);

        jLabel1.setText("tes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 240, 15, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BetConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BetConfirmActionPerformed
        // TODO add your handling code here
        if (ProyekPBONew.getLoggedUser().getSaldo() >= Integer.parseInt(BetField.getText())) {
            //game
            this.getBetField().setVisible(false);
            this.getBetLabel().setVisible(false);
            this.getBetConfirm().setVisible(false);
            this.getCurSaldo().setVisible(false);
            this.getSaldoLabel().setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Input", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BetConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BetConfirm;
    private javax.swing.JTextField BetField;
    private javax.swing.JLabel BetLabel;
    private javax.swing.JLabel CurSaldo;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
