/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyekpbonew;

import java.awt.Image;
import java.util.Stack;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Gary
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        this.setSize(1920, 1080);
        this.getBetField().setBounds(925, 262, 350, 30);
        this.getBetLabel().setBounds(750, 250, 350, 50);
        this.getBetConfirm().setBounds(840, 500, 350, 50);
        this.getCurSaldo().setBounds(925, 200, 350, 50);
        this.getSaldoLabel().setBounds(790, 200, 350, 50);
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/res/background.jpg")); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(1920, 1080, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        BackgroundImage.setIcon(imageIcon);
        BackgroundImage.setBounds(0, 0, 1920, 1080);
        this.setLocationRelativeTo(null);
        this.jLabel1.setVisible(false);
        Stack<Card> Deck = new Stack<>();
        for (int i = 1; i <= 13; i++) {
            Deck.push(new Clubs(i));
        }
//        for (int i = 1; i <= 13; i++) {
//            Deck.push(new Spades(i));
//        }
//        for (int i = 1; i <= 13; i++) {
//            Deck.push(new Diamonds(i));
//        }
//        for (int i = 1; i <= 13; i++) {
//            Deck.push(new Hearts(i));
//        }
    }

    public JLabel getSaldoLabel() {
        return SaldoLabel;
    }

    public JButton getBetConfirm() {
        return BetConfirm;
    }

    public JLabel getCurSaldo() {
        return CurSaldo;
    }

    public JTextField getBetField() {
        return BetField;
    }

    public JLabel getBetLabel() {
        return BetLabel;
    }

    public JLabel getBackgroundImage() {
        return BackgroundImage;
    }

    public void setBackgroundImage(JLabel BackgroundImage) {
        this.BackgroundImage = BackgroundImage;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BetLabel = new javax.swing.JLabel();
        BetField = new javax.swing.JTextField();
        BetConfirm = new javax.swing.JButton();
        CurSaldo = new javax.swing.JLabel();
        SaldoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BetLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BetLabel.setForeground(java.awt.Color.lightGray);
        BetLabel.setText("Input Bet :");
        getContentPane().add(BetLabel);
        BetLabel.setBounds(93, 107, 65, 32);

        BetField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetFieldActionPerformed(evt);
            }
        });
        getContentPane().add(BetField);
        BetField.setBounds(180, 110, 103, 20);

        BetConfirm.setText("OK");
        BetConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(BetConfirm);
        BetConfirm.setBounds(140, 150, 72, 22);

        CurSaldo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CurSaldo.setForeground(java.awt.Color.lightGray);
        getContentPane().add(CurSaldo);
        CurSaldo.setBounds(140, 80, 37, 0);

        SaldoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SaldoLabel.setForeground(java.awt.Color.lightGray);
        SaldoLabel.setText("Saldo :");
        getContentPane().add(SaldoLabel);
        SaldoLabel.setBounds(90, 80, 37, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Flat-Playing-Cards-Set/Flat Playing Cards Set/Back Covers/Pomegranate.png"))); // NOI18N
        jLabel1.setText("tes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 290, 110, 90);

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/background.jpg"))); // NOI18N
        getContentPane().add(BackgroundImage);
        BackgroundImage.setBounds(0, 0, 630, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BetConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BetConfirmActionPerformed
        // TODO add your handling code here
        if (ProyekPBONew.getLoggedUser().getSaldo() >= Integer.parseInt(BetField.getText())) {
            //game
            this.getBetField().setVisible(false);
            this.getBetLabel().setVisible(false);
            this.getBetConfirm().setVisible(false);
            this.getCurSaldo().setVisible(false);
            this.getSaldoLabel().setVisible(false);
            this.jLabel1.setVisible(true);
            ImageIcon imageIcon = new ImageIcon(getClass().getResource("/res/Flat-Playing-Cards-Set/Flat Playing Cards Set/Back Covers/Pomegranate.png")); // load the image to a imageIcon
            Image image = imageIcon.getImage(); // transform it
            Image newimg = image.getScaledInstance(100, 149, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            imageIcon = new ImageIcon(newimg);  // transform it back
            jLabel1.setIcon(imageIcon);
            jLabel1.setBounds(100, 100, 100, 149);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Input", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BetConfirmActionPerformed

    private void BetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BetFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JButton BetConfirm;
    private javax.swing.JTextField BetField;
    private javax.swing.JLabel BetLabel;
    private javax.swing.JLabel CurSaldo;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
